[versions]
indra = "4.0.0"
checkstyle = "13.0.0"
junit = "6.0.2"

[libraries]
jspecify = "org.jspecify:jspecify:1.0.0"
jetbrains-annotations = "org.jetbrains:annotations:26.0.2-1"
gson = "com.google.code.gson:gson:2.13.2"

# ErrorProne
errorprone = "com.google.errorprone:error_prone_core:2.46.0"
nullaway = "com.uber.nullaway:nullaway:0.12.15"

# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }

# unused, for renovate
#noinspection UnusedVersionCatalogEntry
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-checkstyle = { id = "net.kyori.indra.checkstyle", version.ref = "indra" }
blossom = { id = "net.kyori.blossom", version = "2.2.0" }
errorprone = { id = "net.ltgt.errorprone", version = "4.4.0" }
